build:
    image: default-bionic
    environment:
        php:
            version: 8.1.30
            ini:
                xdebug.mode: coverage
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    - command: vendor/bin/phpcs -n --standard=PSR12 --ignore=./vendor/ --extensions=php ./
                    - command: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover /home/scrutinizer/build/clover.xml
                      coverage: 
                        file: /home/scrutinizer/build/clover.xml
                        format: clover
        tests: true
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
